site_name: Group Project 2 -- Intelligent Building Management System through Data-Driven Thermodynamics Modeling and Control

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets

nav:
  - Home: index.md 
  - Engineering Document: literature_review/PROJECT_DOCUMENT.md
  - Database Extraction: db_extraction.md 
  - Database Augmentation: db_augmentation.md 
  - Thermodynamics Modeling: thermodynamics_modeling.md 
  - Slurm pipeline: slurm_pipeline.md 
